#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
#

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #( absolute
      *)    app_path=$APP_HOME$link ;; #( relative
    esac
done
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Shell Script to execute when running Gradle
exec_gradle() {
    "$JAVACMD" "$@"
}

set_java_home () {
    if [ -n "$JAVA_HOME" ] ; then
        if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
            JAVACMD="$JAVA_HOME/jre/sh/java"
        else
            JAVACMD="$JAVA_HOME/bin/java"
        fi
        if [ ! -x "$JAVACMD" ] ; then
            die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
        fi
    else
        JAVACMD="java"
        if ! command -v java >/dev/null 2>&1; then
            die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
        fi
    fi
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

warn () {
    echo "$*"
}

set_java_home
exec "$JAVACMD" \
    $DEFAULT_JVM_OPTS \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
